<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="oleksanddr-chat-mobile-button-wrapper">
    <a href="javascript:void(0);"
       class="oleksandrr-chat-open-button-mobile active"
       data-mage-init='{"oleksandrr_chat_openButton": {}}'
    ><img class="chat-logo" src="<?= $block->escapeUrl($block->getViewFileUrl('Oleksandrr_Chat/images/chat.png')) ?>" alt="<?= $block->escapeHtml(__('Chat')) ?>>"/></a>
</div>
