<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="oleksandrr-chat-sidebar-container" data-bind="scope: 'chatSidebar'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#oleksandrr-chat-sidebar-container": {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
            }
        }
    </script>
</div>
