<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="oleksandrr-chat-window"
     style="display: none;"
     data-mage-init='{"oleksandrr_chat_sidebar": {}}'
>
    <h3><?= $block->escapeHtml(__('Chat with Admin')) ?></h3>

    <div class="oleksandrr-chat-message-field-wrapper">
        <div id="oleksandrr-chat-message-field">

        </div>

    </div>
    <div>
        <label for="oleksandrr-chat-textarea">Enter message</label>
        <textarea id="oleksandrr-chat-textarea"></textarea>
    </div>
    <div class="oleksandrr-chat-button-wrapper">
        <button type="button"
                class="action primary"
                id="oleksandrr-chat-send-button"
        ><?= $block->escapeHtml(__('Send message')) ?></button>
        <button type="button"
                id="oleksandrr-chat-window-close-button"
        ><?= $block->escapeHtml(__('Close')) ?></button>
    </div>
</div>